version: '3.7'
services:
  nginx:
    container_name: v-nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  mysql:
    container_name: v-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: library
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql01/conf:/etc/msyql
      - mysql01/log:/var/log/mysql
      - mysql01/data:/var/lib/mysql

  library:
    restart: always
    build: .
    working_dir: /library
    depends_on:
      - nginx
      - mysql
