server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/library?serverTimezone=GMT%2B8&userSSL=false

  thymeleaf:
    cache: false
