server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/library?serverTimezone=GMT%2B8&userSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    cache: false

  redis:
    host: 119.29.14.37
    port: 6379
    password: 12345
    database: 0

  session:
    store-type: redis
    timeout: 1800



